# Dokploy configuration file
# This file helps Dokploy understand your application structure

version: '1.0'

build:
  dockerfile: Dockerfile
  context: .

deploy:
  port: 3000
  healthcheck:
    path: /api/health
    interval: 30
    timeout: 3
    retries: 3

environment:
  required:
    - DATABASE_URL
  optional:
    - NODE_ENV
    - PORT
    - HOSTNAME
